services:
  app:
    image: node:lts-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 127.0.0.1:3000:3000
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root1234
      DB_NAME: laboratorio_quimica
      PORT: 3000
      JWT_SECRET: mi_clave_secreta_super_segura_123
      JWT_EXPIRES: 1d
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: laboratorio_quimica

  grafana:
    image: grafana/grafana
    container_name: grafana_lab
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - mysql
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  mysql_data:
  grafana_data: